services:
  db:
    image: postgres:17.5-bookworm
    env_file: .env.prod
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    env_file: .env.prod
    # Expose 8000 on the host so cloudflared (host service) can reach it
    ports:
      - "127.0.0.1:8000:8000"
    restart: unless-stopped

volumes:
  pgdata:
