services:
  db:
    image: postgres:17.5-bookworm
    container_name: idea_manager_db
    environment:
      POSTGRES_USER: ideauser
      POSTGRES_PASSWORD: ideapass
      POSTGRES_DB: ideadb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
