services:
  db:
    image: postgres:17.5-bookworm
    container_name: idea_manager_db
    environment:
      POSTGRES_USER: ideauser
      POSTGRES_PASSWORD: ideapass
      POSTGRES_DB: ideadb
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ideauser -d ideadb || exit 1"]
      interval: 2s
      timeout: 3s
      retries: 20
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: idea_manager_api
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - ./:/app                 # hot reload

volumes:
  pgdata:
