"""rename and fix columns in ideas table

Revision ID: bc365be279a1
Revises: 51751b2da735
Create Date: 2025-08-09 06:30:37.669641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc365be279a1'
down_revision: Union[str, Sequence[str], None] = '51751b2da735'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ideas', sa.Column('ease_to_build', sa.Integer(), nullable=True))
    op.drop_column('ideas', 'easy_to_build')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ideas', sa.Column('easy_to_build', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('ideas', 'ease_to_build')
    # ### end Alembic commands ###
