name = "ideas-api-proxy"
main = "src/proxy.ts"
compatibility_date = "2025-04-02"

# Deploy to your workers.dev subdomain first (we'll bind a custom route later)
workers_dev = true

# You can also set these as real secrets/vars in Cloudflare later; fine as defaults here
[vars]
API_ORIGIN = "https://api.eddyb.dev"
ALLOWED_ORIGINS="https://app.eddyb.dev,https://idea-manager.pages.dev"

routes = [
  { pattern = "app.eddyb.dev/api/*", zone_name = "eddyb.dev" }
]